import os
import pandas as pd
from openai import OpenAI


os.environ["OPENAI_API_KEY"] = "sk-..."
# Initialize OpenAI client
client = OpenAI(api_key=os.environ.get("OPENAI_API_KEY"))

def load_extracted_data(excel_file="staff_report.xlsx"):
    """Load the data we extracted earlier"""
    if not os.path.exists(excel_file):
        print(f"❌ {excel_file} not found. Run the scraper first.")
        return None
    
    df = pd.read_excel(excel_file)
    print(f"✅ Loaded {len(df)} records")
    return df

def generate_summary_report(data_df):
    """Use LLM to generate a natural language summary"""
    print("\n🤖 Generating AI summary report...")
    
    # Convert data to text format for the LLM
    data_text = data_df.to_string(index=False)
    
    prompt = f"""
You are a healthcare operations analyst. Review this staff/extracted data and provide:

1. A one-paragraph executive summary
2. Key statistics (total staff, unique roles, etc.)
3. Any anomalies or missing data
4. Recommendations for data quality improvement

Data:
{data_text}

Format your response as a clean, professional report.
"""
    
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",  # or "gpt-4" for better quality
        messages=[
            {"role": "system", "content": "You are a healthcare data analyst. Be concise and professional."},
            {"role": "user", "content": prompt}
        ],
        temperature=0.3,  # Lower = more consistent, factual
        max_tokens=500
    )
    
    summary = response.choices[0].message.content
    return summary

def detect_anomalies(data_df):
    """Ask LLM to find unusual patterns"""
    print("🔍 Detecting anomalies...")
    
    data_text = data_df.to_string(index=False)
    
    prompt = f"""
Analyze this healthcare staff data and identify ANY anomalies, such as:
- Missing employee IDs
- Incomplete names
- Unusual job titles
- Duplicate entries
- Formatting inconsistencies

Data:
{data_text}

List each anomaly with severity (High/Medium/Low) and a suggested fix.
"""
    
    response = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.2,
        max_tokens=400
    )
    
    return response.choices[0].message.content

def generate_structured_report(data_df, summary, anomalies):
    """Create final HTML report with AI content"""
    
    html = f"""
<html>
<head>
    <title>AI-Generated Healthcare Staff Report</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial; margin: 30px; line-height: 1.6; }}
        .header {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 10px; }}
        .summary {{ background: #f0f4ff; padding: 20px; border-radius: 10px; margin: 20px 0; border-left: 4px solid #667eea; }}
        .anomalies {{ background: #fff3f0; padding: 20px; border-radius: 10px; margin: 20px 0; border-left: 4px solid #ff6b6b; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
        th {{ background-color: #667eea; color: white; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        .footer {{ text-align: center; margin-top: 40px; color: #666; font-size: 12px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🏥 Healthcare Staff Intelligence Report</h1>
        <p>AI-Generated Analysis | {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
    
    <div class="summary">
        <h2>📊 Executive Summary</h2>
        <div>{summary.replace(chr(10), '<br>')}</div>
    </div>
    
    <div class="anomalies">
        <h2>⚠️ Detected Anomalies</h2>
        <div>{anomalies.replace(chr(10), '<br>')}</div>
    </div>
    
    <h2>📋 Raw Extracted Data</h2>
    {data_df.to_html(index=False)}
    
    <div class="footer">
        Generated by AI Automation Pipeline | LLM: GPT-3.5-Turbo
    </div>
</body>
</html>
    """
    
    with open("ai_generated_report.html", "w", encoding="utf-8") as f:
        f.write(html)
    print("✅ Saved: ai_generated_report.html")
    
    # Also save as text
    with open("ai_summary.txt", "w", encoding="utf-8") as f:
        f.write("=== AI SUMMARY ===\n\n")
        f.write(summary)
        f.write("\n\n=== ANOMALIES ===\n\n")
        f.write(anomalies)
    print("✅ Saved: ai_summary.txt")

def process_multiple_reports(folder_path="reports"):
    """Process all Excel files in a folder"""
    import glob
    
    excel_files = glob.glob(f"{folder_path}/*.xlsx")
    all_insights = []
    
    for file in excel_files:
        print(f"\n📄 Processing: {file}")
        df = pd.read_excel(file)
        
        # Generate insight for each file
        prompt = f"Summarize this healthcare data in one sentence: {df.to_string()}"
        response = client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=100
        )
        
        all_insights.append({
            "file": file,
            "insight": response.choices[0].message.content,
            "record_count": len(df)
        })
    
    # Generate master summary
    master_prompt = f"Create a 3-bullet executive summary from these insights: {all_insights}"
    # ... call LLM again
    
    return all_insights


# ========== RUN ==========
if __name__ == "__main__":
    # First, make sure we have data
    df = load_extracted_data()
    
    if df is not None and len(df) > 0:
        summary = generate_summary_report(df)
        print("\n" + "="*50)
        print("AI SUMMARY:")
        print("="*50)
        print(summary)
        
        anomalies = detect_anomalies(df)
        print("\n" + "="*50)
        print("ANOMALIES DETECTED:")
        print("="*50)
        print(anomalies)
        
        generate_structured_report(df, summary, anomalies)
        print("\n🎉 AI reporting complete! Open ai_generated_report.html")
    else:
        print("❌ No data available. Run the scraper first to extract staff data.")